name: rspec
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  rspec:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: [2.7, 3.0, 3.1]
        gemfile:
          - rails_5_2
          - rails_6
          - rails_6_1
          - rails_7
          - rails_master
        exclude:
          - ruby: 3.0
            gemfile: rails_5_2
          - ruby: 3.1
            gemfile: rails_5_2
    env:
      BUNDLE_GEMFILE: ${{ github.workspace }}/gemfiles/${{ matrix.gemfile }}.gemfile
    timeout-minutes: 5
    services:
      mysql:
        image: mysql:5.7
        ports:
          - 3306:3306
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: bundle install
        env:
          MATRIX_RAILS_VERSION: ${{ matrix.rails }}
        run: |
          bundle install --jobs 4 --retry 3
      - name: create database
        run: mysql --host 127.0.0.1 --port ${{ job.services.mysql.ports['3306'] }} -uroot -e "create database jinrai_test"
      - name: RSpec
        run: bundle exec rspec
